"""One-time backfill: reassign existing decks to their real GenAI Workspace owners.

Run at cutover, after the `a1f0c2d4e6b8` migration and before switching users onto the Workspace UI.
Dry-run by default; pass --apply to write.

Why this is a script and not an Alembic migration: the deck -> owner mapping comes from the
orchestrator's records (idempotency rows and offer messages), which this database cannot see.
It is generated by the S4 audit and passed in as --mapping. Everything here is deliberately
self-contained (no imports of live application code) so its behaviour stays fixed to what it did
when it was reviewed and run, independent of later edits to the app.

Reassigning `owner_id` alone is NOT enough. Assets are only served from
`app_data/<root>/users/<owner-uuid>/...` (or from the legacy root, admin only), and slide JSON
stores those URLs. So for each attributed deck this script also copies every referenced file into
the new owner's directory and rewrites the URLs. Files are copied, never moved or deleted: another
deck may reference the same file, and originals stay as the rollback path.

Decks that are NOT in the mapping are left completely untouched and listed in the report
(Decision D5: their owner is unresolved).

Usage:
  python scripts/backfill_deck_owners.py --db sqlite:///app_data/fastapi.db \
      --app-data app_data --mapping mapping.json [--apply] [--report report.json]

mapping.json: {"<presentation-uuid>": "<workspace username (JWT sub)>", ...}
"""
import argparse
import json
import os
import re
import shutil
import sys
import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, MetaData, Table, Uuid, create_engine, select, update

ASSET_ROOTS = ("images", "uploads", "exports", "pptx-to-html", "pptx-to-json")
_REF = re.compile(
    r"/app_data/(" + "|".join(ASSET_ROOTS) + r")/"
    r"(users/[0-9a-fA-F-]{36}/)?([^\"'\s)?#\\]+)"
)
_SKIP_COLUMNS = {"id", "owner_id", "presentation", "presentation_id", "created_at", "updated_at"}


def _norm(subject: str) -> str:
    return str(subject or "").strip().lower()


def _safe_rel(rest: str) -> str | None:
    """`rest` must stay inside its root: no traversal, no absolute path."""
    if not rest or rest.startswith("/") or "\x00" in rest:
        return None
    parts = rest.split("/")
    if any(p in ("", ".", "..") for p in parts):
        return None
    return rest


def _get_or_create_user(conn, users: Table, subject: str, apply: bool) -> uuid.UUID:
    row = conn.execute(select(users.c.id).where(users.c.external_subject == subject)).first()
    if row:
        return uuid.UUID(str(row[0]))
    new_id = uuid.uuid4()
    if apply:
        conn.execute(
            users.insert().values(
                id=new_id,
                username=(f"ws:{subject}"[:100] + f"-{new_id.hex[:8]}"),
                external_subject=subject,
                hashed_password="!external",
                is_active=True,
                is_superuser=False,
                is_verified=True,
                auth_version=1,
                created_at=datetime.now(timezone.utc),
            )
        )
    return new_id


def _rewrite_refs(text: str, old_owner: str | None, new_owner: uuid.UUID, app_data: str,
                  apply: bool, stats: dict) -> str:
    def repl(m: re.Match) -> str:
        root, users_prefix, rest = m.group(1), m.group(2), m.group(3)
        ref_owner = users_prefix.split("/")[1].lower() if users_prefix else None
        if ref_owner == str(new_owner):
            return m.group(0)  # already migrated (re-run)
        if ref_owner is not None and ref_owner != (old_owner or "").lower():
            stats["skipped_foreign_refs"].append(m.group(0))  # someone else's file: never touch
            return m.group(0)
        rel = _safe_rel(rest)
        if rel is None:
            stats["skipped_unsafe_refs"].append(m.group(0))
            return m.group(0)
        src = os.path.join(app_data, root, *(users_prefix.split("/")[:2] if users_prefix else []), *rel.split("/"))
        dst = os.path.join(app_data, root, "users", str(new_owner), *rel.split("/"))
        if not os.path.isfile(src):
            stats["missing_files"].append(src)
            return m.group(0)
        if apply and not os.path.exists(dst):
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
        stats["files_copied" if apply else "files_to_copy"] += 1
        return f"/app_data/{root}/users/{new_owner}/{rel}"

    return _REF.sub(repl, text)


def _rewrite_value(value, *args):
    if isinstance(value, str):
        return _rewrite_refs(value, *args)
    if isinstance(value, (dict, list)):
        return json.loads(_rewrite_refs(json.dumps(value), *args))
    return value


def run(db_url: str, app_data: str, mapping: dict[str, str], apply: bool) -> dict:
    engine = create_engine(db_url)
    meta = MetaData()
    # Reflection maps UUID columns to plain strings on SQLite; declare them so ids compare and
    # bind the same way on every dialect.
    def reflect(name: str, *uuid_cols: str) -> Table:
        return Table(name, meta, *(Column(c, Uuid, primary_key=(c == "id")) for c in uuid_cols), autoload_with=engine)

    users = reflect("user", "id")
    decks = reflect("presentations", "id", "owner_id")
    slides = reflect("slides", "id", "owner_id", "presentation")
    chats = reflect("chat_history_messages", "owner_id", "presentation_id")

    report = {"applied": apply, "reassigned": [], "not_found": [], "unattributed": [],
              "files_copied": 0, "files_to_copy": 0, "missing_files": [],
              "skipped_foreign_refs": [], "skipped_unsafe_refs": []}
    wanted = {str(uuid.UUID(k)): _norm(v) for k, v in mapping.items() if _norm(v)}

    with engine.begin() as conn:
        rows = conn.execute(select(decks)).mappings().all()
        seen = set()
        for deck in rows:
            deck_id = str(deck["id"])
            subject = wanted.get(deck_id)
            if subject is None:
                report["unattributed"].append(deck_id)
                continue
            seen.add(deck_id)
            new_owner = _get_or_create_user(conn, users, subject, apply)
            old_owner = str(deck["owner_id"]) if deck["owner_id"] else None
            args = (old_owner, new_owner, app_data, apply, report)

            def rewritten(table, row):
                out = {}
                for col in table.c:
                    if col.name in _SKIP_COLUMNS:
                        continue
                    new = _rewrite_value(row[col.name], *args)
                    if new != row[col.name]:
                        out[col.name] = new
                return out

            if apply:
                changes = rewritten(decks, deck)
                # Pin updated_at: this is a migration, not a user edit.
                conn.execute(update(decks).where(decks.c.id == deck["id"]).values(
                    owner_id=new_owner, updated_at=decks.c.updated_at, **changes))
                for s in conn.execute(select(slides).where(slides.c.presentation == deck["id"])).mappings().all():
                    conn.execute(update(slides).where(slides.c.id == s["id"]).values(
                        owner_id=new_owner, **rewritten(slides, s)))
                conn.execute(update(chats).where(chats.c.presentation_id == deck["id"]).values(owner_id=new_owner))
            else:
                rewritten(decks, deck)
                for s in conn.execute(select(slides).where(slides.c.presentation == deck["id"])).mappings().all():
                    rewritten(slides, s)
            report["reassigned"].append({"presentation_id": deck_id, "subject": subject,
                                         "from_owner": old_owner, "to_owner": str(new_owner)})
        report["not_found"] = sorted(set(wanted) - seen)
    return report


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", required=True)
    ap.add_argument("--app-data", required=True)
    ap.add_argument("--mapping", required=True)
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--report")
    a = ap.parse_args()
    report = run(a.db, a.app_data, json.load(open(a.mapping)), a.apply)
    text = json.dumps(report, indent=2)
    if a.report:
        open(a.report, "w").write(text)
    print(("APPLIED" if a.apply else "DRY RUN (nothing written)"), "-",
          f"{len(report['reassigned'])} decks reassigned, {len(report['unattributed'])} unattributed left untouched, "
          f"{len(report['not_found'])} mapping entries with no deck, {len(report['missing_files'])} referenced files missing")
    return 0


if __name__ == "__main__":
    sys.exit(main())
