"""Studio Oracle baseline with durable presentation-create outcomes.

The v1 baseline remains frozen for existing installations. This module performs
pure SQL generation and never reads environment values or connects to a database.
"""
from sqlalchemy import Column, ForeignKey, Table
from sqlalchemy.dialects import oracle
from sqlalchemy.schema import CreateIndex, CreateTable
from dbschema.oracle_v1 import PREDECESSOR, TRACKER, build_metadata as build_v1

REVISION = "b0c2d4e6f8a1"
BASELINE_REVISION = "a9b2c4d6e8f0"
OPERATION_TABLE = "GENAI_WORKSPACE_STUDIO_OPERATION"


def build_metadata(*, include_tracker=False):
    metadata = build_v1(include_tracker=include_tracker)
    Table(OPERATION_TABLE, metadata,
          Column("operation_key", oracle.VARCHAR2(64), primary_key=True, nullable=False),
          Column("operation_id", oracle.VARCHAR2(128), nullable=False),
          Column("owner_id", oracle.RAW(16), ForeignKey("GENAI_WORKSPACE_STUDIO_USER.id", ondelete="CASCADE"), nullable=False),
          Column("request_hash", oracle.VARCHAR2(64), nullable=False),
          Column("presentation_id", oracle.RAW(16), nullable=False),
          Column("created_at", oracle.TIMESTAMP(timezone=True), nullable=False))
    return metadata


def render_sql():
    dialect = oracle.dialect()
    metadata = build_metadata(include_tracker=True)
    statements = ["-- Generated by AI-Presentation-Studio: python -m dbschema.oracle_v2",
                  "-- Run as the dedicated Studio schema owner; never the Workspace owner.",
                  "-- Fresh schema only. Existing installations use Alembic upgrade head."]
    for table in metadata.sorted_tables:
        statement = str(CreateTable(table).compile(dialect=dialect)).strip()
        if table.name == OPERATION_TABLE:
            statement = "\n".join(line.rstrip() for line in statement.splitlines())
        statements.append(statement + ";")
        for index in sorted(table.indexes, key=lambda i: i.name):
            statements.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
    statements.extend([f'INSERT INTO "{TRACKER}" (version_num) VALUES (\'{REVISION}\');', "COMMIT;"])
    return "\n\n".join(statements) + "\n"


if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")
    sys.stdout.write(render_sql())
